import socket 
server=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
server.bind(("127.0.0.1",5102))
server.listen(1)
print("Server is Listening....")
client_socket,address=server.accept()
print("Connected by :",address)
message=client_socket.recv(1024).decode()
print("Client Says:",message)
client_socket.send("Hello From Server".encode())
client_socket.close()
server.close()